Repository VolunteerPlatform/backend, pull requests merged in 2022-09, with the labels that each got.

#12 #11 봉사활동 검색 구현하기
  volunteer_platform/build.gradle
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/SearchCondition.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/VolActController.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/VolAppController.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/VolOrganController.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/dto/SearchResultDto.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/form/ActivityForm.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/form/ActivityTimeForm.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/converter/CustomResponse.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/models/Address.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/models/Coordinate.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/models/VolActivity.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/models/VolActivitySession.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/models/VolOrgan.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/repository/CustomSearchRepository.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/VolActivityServiceImpl.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/VolAppServiceImpl.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/volinterface/VolActivityService.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/volinterface/VolAppService.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/global/configuration/BeanConfiguration.java
Labels: 신규 개발, 리펙토링

#16 Refactoring/volunteer
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/VolActController.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/VolAppController.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/VolOrganController.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/dto/VolActivityIdDto.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/dto/VolOrganIdDto.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/repository/CustomVolAppRepository.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/repository/VolActivitySessionRepository.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/repository/VolAppRepository.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/VolActivityServiceImpl.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/VolAppServiceImpl.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/VolOrganServiceImpl.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/volinterface/VolActivityService.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/volinterface/VolAppService.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/volinterface/VolOrganService.java
Labels: 리펙토링

#18 Feat: 찜하기 기능 구현
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/member/controller/MemberProfileController.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/member/service/MemberServiceImpl.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/WishListController.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/form/WishListForm.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/models/WishList.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/repository/WishListRepository.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/WishListServiceImpl.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/volinterface/WishListService.java
Labels: 신규 개발, 리펙토링, BackEnd

#19 Volunteer -> Develop
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/VolActController.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/dto/VolActivitySessionDto.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/models/VolActivity.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/models/VolActivitySession.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/models/enumtype/SessionStatus.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/repository/VolActivitySessionRepository.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/VolActivityServiceImpl.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/VolAppServiceImpl.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/volinterface/VolActivityService.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/global/advice/CustomControllerAdvice.java
Labels: 신규 개발, 이슈

#22 Edit: 회원 관리자 등록시 권한 부여 추가
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/config/SecurityConfig.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/member/controller/LoginController.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/member/form/CenterForm.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/member/form/MemberForm.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/member/service/MemberServiceImpl.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/member/service/memberinterface/MemberService.java
Labels: BackEnd, HotFix

#23 DevelopV0.2
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/config/SecurityConfig.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/member/controller/LoginController.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/member/form/CenterForm.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/member/form/MemberForm.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/member/service/MemberServiceImpl.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/member/service/memberinterface/MemberService.java
Labels: 배포

#24 Feature/volunteer -> Develop
  volunteer_platform/build.gradle
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/VolActController.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/VolOrganController.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/dto/AppHistoryDto.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/dto/VolActivityIdDto.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/form/ActivityModifyForm.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/models/VolActivity.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/models/VolOrgan.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/repository/VolOrganRepository.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/VolActivityServiceImpl.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/VolOrganServiceImpl.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/volinterface/VolActivityService.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/volinterface/VolOrganService.java
  volunteer_platform/src/test/java/com/volunteer_platform/volunteer_platform/domain/volunteer/integration/VolActivityIntegrationTest.java
  volunteer_platform/src/test/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/VolAppServiceConcurrencyTest.java
  volunteer_platform/src/test/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/VolAppServiceImplTest.java
  volunteer_platform/src/test/resources/application.yml
  volunteer_platform/src/test/resources/json/VolRequest.json
Labels: 테스트, 리펙토링, 이슈

#25 DevelopV0.3
  volunteer_platform/build.gradle
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/VolActController.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/VolOrganController.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/dto/AppHistoryDto.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/dto/VolActivityIdDto.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/controller/form/ActivityModifyForm.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/models/VolActivity.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/models/VolOrgan.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/repository/VolOrganRepository.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/VolActivityServiceImpl.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/VolOrganServiceImpl.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/volinterface/VolActivityService.java
  volunteer_platform/src/main/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/volinterface/VolOrganService.java
  volunteer_platform/src/test/java/com/volunteer_platform/volunteer_platform/domain/volunteer/integration/VolActivityIntegrationTest.java
  volunteer_platform/src/test/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/VolAppServiceConcurrencyTest.java
  volunteer_platform/src/test/java/com/volunteer_platform/volunteer_platform/domain/volunteer/service/VolAppServiceImplTest.java
  volunteer_platform/src/test/resources/application.yml
  volunteer_platform/src/test/resources/json/VolRequest.json
Labels: 배포
